server:
  port: 5210
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disable-date?useSSL=false
    username: root
    password: 2000516
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true