spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    mode: HTML
  datasource:
    url: jdbc:mysql://localhost:3306/disable-date?useSSL=false
    username: root
    password: 2000516
    driver-class-name: com.mysql.cj.jdbc.Driver
    rabbitmq:
      host: 222.177.66.230
      port: 5672
      username: admin
      password: admin
      virtual-host: /disable
      listener:
        simple:
          prefetch: 1     #（设置preFetch这个值，可以控制预取消息的上限）每次只能获取一条消息，处理完成才能获取下一个消息
server:
  port: 5210
mybatis:
  configuration:
    map-underscore-to-camel-case: true
